-- Nairrative database schema
-- Paste this into the Supabase SQL editor to set up the database from scratch.
--
-- IMPORTANT: Two policies below (books_select, book_authors_select) contain a
-- hardcoded owner UUID. This allows unauthenticated visitors to browse the
-- owner's library as a public reading list. After signing up, replace every
-- occurrence of <YOUR_USER_ID> with your actual Supabase auth.uid().

-- ── authors ───────────────────────────────────────────────────────────────────

create table public.authors (
  id    integer generated by default as identity primary key,
  name  text not null unique,
  country text
);

alter table public.authors enable row level security;

create policy "Public can read authors"
  on public.authors for select to public using (true);

create policy "Authenticated users can insert authors"
  on public.authors for insert to authenticated with check (true);

create policy "Authenticated users can update authors"
  on public.authors for update to authenticated using (true) with check (true);

create policy "Authenticated users can delete authors"
  on public.authors for delete to authenticated using (true);


-- ── books ─────────────────────────────────────────────────────────────────────

create table public.books (
  id               integer generated by default as identity primary key,
  user_id          uuid references auth.users(id),
  title            text not null,
  year_read_start  integer,
  year_read_end    integer,
  genre            text[],
  format           text check (format = any (array[
                     'Novel','Novella','Short Stories','Graphic Novel','Non-Fiction','Play'
                   ])),
  fiction          boolean default true,
  series           text default '',
  series_number    numeric[],
  pages            integer,
  user_added       boolean default false,
  cover_url        text,
  rating           text check (rating = any (array[
                     'transformative','loved','enjoyed','meh','dont_remember','dropped','didnt_like'
                   ])),
  theme            text[],
  mood             text,
  narrative_style  text,
  setting_era      text,
  archetype        text,
  created_at       timestamptz default now(),
  updated_at       timestamptz default now()
);

alter table public.books enable row level security;

-- Replace <YOUR_USER_ID> so unauthenticated visitors can read your library.
create policy "books_select"
  on public.books for select to public using (
    user_id = '<YOUR_USER_ID>'::uuid or auth.uid() = user_id
  );

create policy "books_insert"
  on public.books for insert to authenticated with check (auth.uid() = user_id);

create policy "books_update"
  on public.books for update to authenticated
  using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "books_delete"
  on public.books for delete to authenticated using (auth.uid() = user_id);

-- Required so the anon role can execute the books_select policy above.
grant select on public.books to anon;


-- ── book_authors ──────────────────────────────────────────────────────────────

create table public.book_authors (
  book_id      integer references public.books(id) on delete cascade,
  author_id    integer references public.authors(id) on delete cascade,
  author_order integer default 1,
  primary key (book_id, author_id)
);

alter table public.book_authors enable row level security;

-- Replace <YOUR_USER_ID> to match the books_select policy above.
create policy "book_authors_select"
  on public.book_authors for select to public using (
    exists (
      select 1 from public.books
      where books.id = book_authors.book_id
        and (books.user_id = '<YOUR_USER_ID>'::uuid or books.user_id = auth.uid())
    )
  );

create policy "book_authors_insert"
  on public.book_authors for insert to authenticated with check (
    exists (
      select 1 from public.books
      where books.id = book_authors.book_id and books.user_id = auth.uid()
    )
  );

create policy "book_authors_delete"
  on public.book_authors for delete to authenticated using (
    exists (
      select 1 from public.books
      where books.id = book_authors.book_id and books.user_id = auth.uid()
    )
  );


-- ── genres ────────────────────────────────────────────────────────────────────

create table public.genres (
  id         integer generated by default as identity primary key,
  name       text not null unique,
  color      text not null,
  sort_order integer default 0
);

alter table public.genres enable row level security;

create policy "Public can read genres"
  on public.genres for select to public using (true);

create policy "Authenticated users can add genres"
  on public.genres for insert to authenticated with check (true);


-- ── analysis_cache ────────────────────────────────────────────────────────────

create table public.analysis_cache (
  id          integer generated by default as identity primary key,
  user_id     uuid references auth.users(id),
  fingerprint text,
  data        jsonb not null,
  created_at  timestamptz default now(),
  updated_at  timestamptz default now()
);

alter table public.analysis_cache enable row level security;

-- Replace <YOUR_USER_ID> so unauthenticated visitors can read your cached analysis.
create policy "analysis_cache_select"
  on public.analysis_cache for select to public using (
    user_id = '<YOUR_USER_ID>'::uuid or auth.uid() = user_id
  );

create policy "analysis_cache_write"
  on public.analysis_cache for all to authenticated
  using (auth.uid() = user_id) with check (auth.uid() = user_id);


-- ── recs_cache ────────────────────────────────────────────────────────────────

create table public.recs_cache (
  id          integer generated by default as identity primary key,
  user_id     uuid references auth.users(id),
  fingerprint text,
  data        jsonb not null,
  created_at  timestamptz default now(),
  updated_at  timestamptz default now()
);

alter table public.recs_cache enable row level security;

-- Replace <YOUR_USER_ID> so unauthenticated visitors can read your cached recommendations.
create policy "recs_cache_select"
  on public.recs_cache for select to public using (
    user_id = '<YOUR_USER_ID>'::uuid or auth.uid() = user_id
  );

create policy "recs_cache_write"
  on public.recs_cache for all to authenticated
  using (auth.uid() = user_id) with check (auth.uid() = user_id);


-- ── panel_prompts ─────────────────────────────────────────────────────────────

create table public.panel_prompts (
  id         integer generated by default as identity primary key,
  user_id    uuid references auth.users(id),
  data       jsonb not null,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.panel_prompts enable row level security;

create policy "panel_prompts_select"
  on public.panel_prompts for select to public using (auth.uid() = user_id);

create policy "panel_prompts_write"
  on public.panel_prompts for all to authenticated
  using (auth.uid() = user_id) with check (auth.uid() = user_id);


-- ── new_releases ──────────────────────────────────────────────────────────────
-- Populated by the scheduled Edge Function (supabase/functions/check-releases).

create table public.new_releases (
  id              uuid primary key default gen_random_uuid(),
  title           text not null,
  author          text not null,
  series          text,
  published_date  text,
  description     text,
  cover_url       text,
  google_books_id text unique,
  detected_at     timestamptz default now(),
  dismissed       boolean default false
);

alter table public.new_releases enable row level security;

create policy "public read"
  on public.new_releases for select to public using (true);

create policy "authenticated write"
  on public.new_releases for all to public using (auth.role() = 'authenticated');
